# Generated by Django 4.2.6 on 2023-12-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hobbyname_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hobbyname', models.CharField(max_length=20)),
            ],
        ),
    ]
