# Generated by Django 4.2.6 on 2024-01-02 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site_admin', '0003_hobbyfactor_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='season_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Season', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='seasonfactor_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Factorname', models.CharField(max_length=20)),
                ('Season_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site_admin.season_tb')),
            ],
        ),
    ]
