# Generated by Django 4.2.6 on 2024-01-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_admin', '0004_season_tb_seasonfactor_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='agefactor_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MinimumAge', models.IntegerField()),
                ('MaximumAge', models.IntegerField()),
                ('Factorname', models.CharField(max_length=20)),
            ],
        ),
    ]
