# Generated by Django 4.2.6 on 2024-01-18 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_customerhobby_tb'),
        ('Site_admin', '0005_agefactor_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='seasoncountry_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month', models.IntegerField()),
                ('Countryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.country_tb')),
                ('SeasonFactorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site_admin.seasonfactor_tb')),
                ('Seasonid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site_admin.season_tb')),
                ('Stateid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.state_tb')),
            ],
        ),
    ]
