# Generated by Django 4.2.6 on 2024-01-12 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_contact_tb_blocklist_tb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_tb',
            name='Contactid',
        ),
        migrations.DeleteModel(
            name='blocklist_tb',
        ),
        migrations.DeleteModel(
            name='contact_tb',
        ),
    ]
